import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "@/app/globals.css";

const font = Rubik({
	variable: "--font-rubik",
	subsets: ["latin"],
	weight: ["300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${font.className} antialiased bg-zinc-950 h-screen 2xl:overflow-y-hidden`}>
				{children}
			</body>
		</html>
	);
}
